# Generated by Django 5.2 on 2025-04-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('active_under_contract', 'Active Under Contract'), ('pending', 'Pending'), ('sold', 'Sold'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='available', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
